package bzu_graph;

import java.awt.Color;

import java.awt.Graphics;
import java.util.List;

import javax.swing.JOptionPane;

public class Main1 extends javax.swing.JFrame {
	String Source;
    String Distenation;
    Vertices newSource;
    Vertices newDistenation;
    static int count=0;
   
    int i=0;

	static Vertices places[]=new Vertices[32];
	static Vertices v;
	

    /**
     * Creates new form NewJFrame
     */
    public Main1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	 
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        label20 = new java.awt.Label();
        label21 = new java.awt.Label();
        label22 = new java.awt.Label();
        label23 = new java.awt.Label();
        label24 = new java.awt.Label();
        label25 = new java.awt.Label();
        label26 = new java.awt.Label();
        label27 = new java.awt.Label();
        label28 = new java.awt.Label();
        label29 = new java.awt.Label();
        label30 = new java.awt.Label();
        label31 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
     
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();

        setTitle("الأقصى 44 دونما");
        setBackground(java.awt.Color.red);
        setForeground(java.awt.Color.red);

        jPanel1.setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label1.setName("مسجد قبة الصخرة"); // NOI18N
        label1.setText("مسجد قبة الصخرة");
        label1.setVisible(false);
        jPanel1.add(label1);
        label1.setBounds(330, 160, 120, 30);

        label2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        label2.setName("المسجد القبلي"); // NOI18N
        label2.setText("المسجد القبلي");
        label2.setVisible(false);
        jPanel1.add(label2);
        label2.setBounds(300, 300, 110, 30);

        label3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label3.setName("حائط البراق"); // NOI18N
        label3.setText("حائط البراق");
        label3.setVisible(false);
        jPanel1.add(label3);
        label3.setBounds(100, 250, 76, 20);

        label4.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label4.setName("باب المغاربة"); // NOI18N
        label4.setText("باب المغاربة");
        label4.setVisible(false);
        jPanel1.add(label4);
        label4.setBounds(60, 280, 80, 20);

        label5.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label5.setName("باب الأسباط"); // NOI18N
        label5.setText("باب الأسباط ");
        label5.setVisible(false);
        jPanel1.add(label5);
        label5.setBounds(768, 40, 80, 20);

        label6.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label6.setName("باب الرحمة"); // NOI18N
        label6.setText("باب الرحمة");
        label6.setVisible(false);
        jPanel1.add(label6);
        label6.setBounds(760, 120, 70, 20);

        label7.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label7.setName("مئذنة الأسباط"); // NOI18N
        label7.setText("مئذنة الأسباط");
        label7.setVisible(false);
        jPanel1.add(label7);
        label7.setBounds(628, 50, 90, 20);

        label8.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label8.setName("باب حطة"); // NOI18N
        label8.setText("باب حطة");
        label8.setVisible(false);
        jPanel1.add(label8);
        label8.setBounds(440, 20, 60, 20);

        label9.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label9.setName("باب العتمة"); // NOI18N
        label9.setText("باب العتمة");
        label9.setVisible(false);
        jPanel1.add(label9);
        label9.setBounds(280, 10, 100, 20);

        label10.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label10.setName("قبة سلبمان"); // NOI18N
        label10.setText("قبة سلبمان");
        label10.setVisible(false);
        jPanel1.add(label10);
        label10.setBounds(270, 50, 90, 20);

        label11.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label11.setName("باب المطهرة"); // NOI18N
        label11.setText("باب المطهرة");
        label11.setVisible(false);
        jPanel1.add(label11);
        label11.setBounds(130, 130, 90, 20);

        label12.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label12.setName("سبيل قيتباي"); // NOI18N
        label12.setText("سبيل قيتباي");
        label12.setVisible(false);
        jPanel1.add(label12);
        label12.setBounds(150, 150, 80, 20);

        label13.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label13.setName("المتحف"); // NOI18N
        label13.setText("المتحف");
        label13.setVisible(false);
        jPanel1.add(label13);
        label13.setBounds(100, 310, 50, 20);

        label14.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label14.setName("مئذنة باب المغاربة\\ المئذنة الفخارية"); // NOI18N
        label14.setText("مئذنة باب المغاربة\\ المئذنة الفخارية");
        label14.setVisible(false);
        jPanel1.add(label14);
        label14.setBounds(10, 360, 220, 20);

        label15.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label15.setName("المصلى المرواني "); // NOI18N
        label15.setText("المصلى المرواني ");
        label15.setVisible(false);
        jPanel1.add(label15);
        label15.setBounds(695, 330, 70, 20);

        label16.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label16.setName("مصطبة الصنوبر"); // NOI18N
        label16.setText("مصطبة الصنوبر");
        label16.setVisible(false);
        jPanel1.add(label16);
        label16.setBounds(190, 280, 100, 20);

        label17.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label17.setName("منبر برهان الدين "); // NOI18N
        label17.setText("منبر برهان الدين ");
        label17.setVisible(false);
        jPanel1.add(label17);
        label17.setBounds(310, 190, 110, 20);

        label18.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label18.setName("قبة السلسلة"); // NOI18N
        label18.setText("قبة السلسلة");
        label18.setVisible(false);
        jPanel1.add(label18);
        label18.setBounds(480, 150, 90, 20);

        label19.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label19.setName("مئذنة باب السلسلة "); // NOI18N
        label19.setText("مئذنة باب السلسلة ");
        label19.setVisible(false);
        jPanel1.add(label19);
        label19.setBounds(20, 150, 120, 20);

        label20.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label20.setName("قبة النحوية"); // NOI18N
        label20.setText("قبة النحوية");
        label20.setVisible(false);
        jPanel1.add(label20);
        label20.setBounds(230, 180, 70, 20);

        label21.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label21.setName("باب السلسلة"); // NOI18N
        label21.setText("باب السلسلة");
        label21.setVisible(false);
        jPanel1.add(label21);
        label21.setBounds(25, 180, 90, 30);

        label22.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label22.setName("مئذنة باب الغوانمة"); // NOI18N
        label22.setText("مئذنة باب الغوانمة");
        label22.setVisible(false);
        jPanel1.add(label22);
        label22.setBounds(160, 10, 110, 20);

        label23.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label23.setName(" باب الغوانمة"); // NOI18N
        label23.setText(" باب الغوانمة");
        label23.setVisible(false);
        jPanel1.add(label23);
        label23.setBounds(170, 40, 80, 20);

        label24.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label24.setName("باب الناظر"); // NOI18N
        label24.setText("باب الناظر");
        label24.setVisible(false);
        jPanel1.add(label24);
        label24.setBounds(140, 70, 70, 20);

        label25.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label25.setName("باب الحديد"); // NOI18N
        label25.setText("باب الحديد");
        label25.setVisible(false);
        jPanel1.add(label25);
        label25.setBounds(130, 90, 70, 20);

        label26.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label26.setName(" باب القطانين"); // NOI18N
        label26.setText(" باب القطانين");
        label26.setVisible(false);
        jPanel1.add(label26);
        label26.setBounds(130, 110, 86, 20);

        label27.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label27.setName("قبة المعراج "); // NOI18N
        label27.setText("قبة المعراج ");
        label27.setVisible(false);
        jPanel1.add(label27);
        label27.setBounds(240, 150, 80, 20);

        label28.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label28.setName(" قبة الشيخ الخليلي"); // NOI18N
        label28.setText(" قبة الشيخ الخليلي ");
        label28.setVisible(false);
        jPanel1.add(label28);
        label28.setBounds(230, 110, 120, 20);

        label29.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label29.setName("قبة النبي موسى"); // NOI18N
        label29.setText("قبة النبي موسى ");
        label29.setVisible(false);
        jPanel1.add(label29);
        label29.setBounds(40, 180, 110, 20);

        label30.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label30.setName(" سبيل سليمان"); // NOI18N
        label30.setText(" سبيل سليمان");
        label30.setVisible(false);
        jPanel1.add(label30);
        label30.setBounds(450, 60, 94, 20);

        label31.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label31.setName("سبيل الكأس"); // NOI18N
        label31.setText("سبيل الكأس");
        label31.setVisible(false);
        jPanel1.add(label31);
        label31.setBounds(340, 250, 80, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("./bzu.p")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 858, 525);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("المصدر:");

        jComboBox1.setBackground(java.awt.Color.gray);
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setMaximumRowCount(35);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"��",label1.getName(),label2.getName(),label3.getName(),label4.getName(),label5.getName(),label6.getName(),label8.getName(),label9.getName(),label10.getName(),label11.getName(),label12.getName(),label13.getName(),label14.getName(),label15.getName(),label16.getName(),label18.getName(),label19.getName(),label20.getName(),label21.getName(),label22.getName(),label23.getName(),label24.getName(),label25.getName(),label26.getName(),label27.getName(),label29.getName(),label30.getName(),label31.getName()}));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("الهدف: ");

        jComboBox2.setBackground(java.awt.Color.gray);
        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setMaximumRowCount(35);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "���",label1.getName(),label2.getName(),label3.getName(),label4.getName(),label5.getName(),label6.getName(),label8.getName(),label9.getName(),label10.getName(),label11.getName(),label12.getName(),label13.getName(),label14.getName(),label15.getName(),label16.getName(),label18.getName(),label19.getName(),label20.getName(),label21.getName(),label22.getName(),label23.getName(),label24.getName(),label25.getName(),label26.getName(),label27.getName(),label29.getName(),label30.getName(),label31.getName() }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("المسار :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setBackground(java.awt.Color.red);
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("بحث");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("المسافة :");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

      

      

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("الإحداثيات:");

        jLabel7.setText("x :");

        jLabel8.setText("y :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("معلومات عامة :");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton4.setBackground(java.awt.Color.red);
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("خروج");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(66, 66, 66)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGap(152, 152, 152)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(jTextField3))
                        .addContainerGap())
                    .addComponent(jScrollPane2)))
        );

        pack();
    }// </editor-fold>                        

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {                                   
        int x =evt.getX();
int y=evt.getY();
if (x>305&&x<424&&y>90&&y<190){
    
label1.setVisible(true);
}
else
      label1.setVisible(false);
if (x>445&&x<475&&y>148&&y<180){
    label18.setVisible(true);
}else
    label18.setVisible(false);
if(x>250&&x<405&&y>295&&y<368){
    label2.setVisible(true);
}
    else
    label2.setVisible(false);
if(x>81&&x<85&&y>317&&y<358){
    label14.setVisible(true);
}
else
    label14.setVisible(false);
if(x>65&&x<95&&y>300&&y<355){
    label13.setVisible(true);
}else
    label13.setVisible(false);
if(y>245&&y<288&&x<86&&x>52){
    label3.setVisible(true);
}
    else
    label3.setVisible(false);

if(x>46&&x<60&&y>298&&y<312){
    label4.setVisible(true);
}else
    label4.setVisible(false);
if(x>539&&x<830&&y>274&&y<407){
    label15.setVisible(true);
}else 
    label15.setVisible(false);
if(x>278&&x<289&&y>128&&y<151){
    label27.setVisible(true);
}else
    label27.setVisible(false);
if(x>265&&x<275&&y>124&&y<137){
    label28.setVisible(true);
}else
    label28.setVisible(false);
if(x>211&&x<272&&y>207&&y<225){
    label20.setVisible(true);
   
}else
    label20.setVisible(false);
if(x>771&&x<818&&y>130&&y<155){
    label6.setVisible(true);
}else
    label6.setVisible(false);
if(x>329&&x<351&&y>276&&y<282){
    label31.setVisible(true);
    
}else
    label31.setVisible(false);
  if(x>797&&x<813&&y<71&&y>40) {
      label5.setVisible(true);
      
  }   else
      label5.setVisible(false);
  if(x>682&&x<690&&y>13&&y<48){
      label7.setVisible(true);
  }else
      label7.setVisible(false);
  if(x>426&&x<444&&y>29&&y<51){
      label8.setVisible(true);
  }else
      label8.setVisible(false);
  if(x>310&&x<343&&y>17&&y<46){
      label9.setVisible(true);
  }
  else
      label9.setVisible(false);
  if(x>442&&x<456&&y<64&&y>52){
     label30.setVisible(true);
  }else
    label30.setVisible(false);
  if(x>168&&x<203&&y>295&&y<310){
   label16.setVisible(true);
  }else
      label16.setVisible(false);
  if(x>177&&x<195&&y>4&&y<25){
      label22.setVisible(true);
  }else
      label22.setVisible(false);
  if(x>155&&x<173&&y>50&&y<64){
      label24.setVisible(true);
  }else
      label24.setVisible(false);
  if(x>149&&x<166&&y>19&&y<33){
      label23.setVisible(true);
  }else
      label23.setVisible(false);
  if(y>150&&y<163&&x>121&&x<135){
      label26.setVisible(true);
  }else
      label26.setVisible(false);
  if(x>148&&x<157&&y>97&&y<122){
      label25.setVisible(true);
  }else
      label25.setVisible(false);
  if(x>113&&x<136&&y>183&&y<209){
      label11.setVisible(true);
  }else
      label11.setVisible(false);
  if(y>158&&y<185&&x>158&&x<170){
      label12.setVisible(true);
  }else
      label12.setVisible(false);
if(x>348&&x<364&&y>46&&y<65){
    label10.setVisible(true);
}else
    label10.setVisible(false);
if(x>154&&x<170&&y>193&&y<206){
    label29.setVisible(true);
}else
    label29.setVisible(false);
if(x>97&&x<104&&y>137&&y<183){
   label19.setVisible(true); 
}else
    label19.setVisible(false);
if(x>78&&x<105&&y>219&&y<233){
    label21.setVisible(true);
}else
    label21.setVisible(false);
if(x>302&&x<318&&y>208&&y<227){
    label17.setVisible(true);
}else
    label17.setVisible(false);
    }                                  

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {                                     
int x =evt.getX();
int y=evt.getY();
jTextField2.setText(x+"متر");
jTextField3.setText(y+"متر");

if (x>305&&x<424&&y>90&&y<190){
	jTextArea2.setText("");
jTextArea2.append(": ���� ���� ������ \n"); 
jTextArea2.append("  ���� ��� ����� �� ����� ��� 685-691 \n "+"��� ���� ���� ������� �� ���� ����� ������ ������ ���� ���� ��� ����� �������� ������� \n "+"������� �� ������ ������ ������� ��� ����� �� ������ 1.5 ���� ���� 13-18 ���� \n"+"���� ����� ������ �������� 35 � ������ 20 � ������ ���� ���� 5 � ");
}

if (x>445&&x<475&&y>148&&y<180){
	jTextArea2.setText("");
jTextArea2.append(label18.getName()+"\n");
jTextArea2.append("���� ������� �� ��� ��� ����� ������ ���� ���� ���� ������� �� ��� ����ɡ\n ���� ���� ������ ������ ���� ����� ����� ����� ����� �������� ��� ��� ������ ���� ������ ������ ��� �� ���� ��� ��� ����� �� ��� ������� ������ ������� ������� ��� ���� ��� ��� ���� ����� ���� ��� ������\n ��� ���� ��� ����� ������� �� �������� ������ ��� ������� �� ��� ������� ������ �������� �� ����� 16�");
}
if(x>250&&x<405&&y>295&&y<368){
	jTextArea2.setText("");
    jTextArea2.append(label2.getName()+"\n");
    jTextArea2.append("��� ������ ������� ���� ����� ��� ������ , ���� �� ����� ������� �� ������ ������ �� ��� ������ \n ���� ���� �� 7 ����� , ���� ���� �� ����� �3 ����� �� �� ���� \n���� ������ 4 ������ ������ ��� 11 ���� ����� � 5500 ���� \n ������ : ���� 80 ���� ����� 55 ���� \n ����� ����� : ��� ����� ��� �� ������ �� ���� �� ��� ������ �� ��� ����� ��� ���� ��� �� ���� ����� ������� ");
}
   
if(x>81&&x<85&&y>317&&y<358){
	jTextArea2.setText("");
	jTextArea2.append(label14.getName()+"\n");
	jTextArea2.append("����� ����� �������� ����� ���� ������� �������� ��� ����� ���� �� ������ �� ��� 1278 �\n ���� ��� ������� �������� ������� �� ������ ������ ��� ����� �� ��� �������� ������� ��� ����� ������� ������ ����� ������ ������ ���� ������ ������ ������ߡ[88] ���� ��� ����� �� ������� �������� �����.\n ����� ��������� ���� ��� ��� ����� ������� ���� ������ ��� ����� ��� ������ ���� ���� ��� ���� ������.[89] ��� ���� ������� ��� ������ ������ �������� �� ���� ����� ����� ����� �����ϡ ����� ��� ����� ����� ���� ��� �������� ������� ���� ������.  \n����� ������ ���� ����� ���� ����� ������ ��� ��� ����� ����� �������");
}

if(x>65&&x<95&&y>300&&y<355){
	jTextArea2.setText("");
	jTextArea2.append(label13.getName()+"\n");
	jTextArea2.append("���� �� ����� ������ ������ ��� ��� ����� �� ������ ������ �� ����� �������.\n ����� ������ ��� ���� �� ���� ��� �� ������� ��������.");
}
if(y>245&&y<288&&x<86&&x>52){
	jTextArea2.setText("");
	jTextArea2.append(label3.getName()+"\n");
	jTextArea2.append("��� �� ������ ������ ������ ������ ������� ���� ��� ��� �������� ����ǡ\n �������� �������� ����ǡ ����� ���� ����� 50�, ��� ������� ���� �� 20 ���,\n ��� ��� ���� ����� ��� ����� ���� ��� ���� ���� ���� ��� ����� ������ ��� ��� ������ ��� ������ ��� ������ ������ �������");
}
   
if(x>46&&x<60&&y>298&&y<312){
   jTextArea2.setText("");
   jTextArea2.append(label4.getName()+"\n");
   jTextArea2.append("(��� �����) (��� ������)\n �� ���� ����� ������ ������ �������ɡ ���� �� ������� ������� �������� ����� ������ ������\n ���� ���� �������� ���� ���� ��� ���� �������� ��� ������, ����� ���� ���� ������, ���� �����,\n ��� ����� �� ������ ���� ��� ���� ���� ���� ��� ��� ��� ������ ������ ������� ���� ������� ��������");
}
if(x>539&&x<830&&y>274&&y<407){
    jTextArea2.setText("");
    jTextArea2.append(label15.getName()+"\n");
    jTextArea2.append("  ������  ���� �� 4000 ���� ����� \n������ ��� 16 ����� ���� ���� ����� ���� ��� ��� �����  ");
}
if(x>278&&x<289&&y>128&&y<151){
   jTextArea2.setText("");
   jTextArea2.append(label27.getName()+"\n");
   jTextArea2.append("���� ��� ������� ���� ������ ������ ������� ��� ������ ������ �� ��� ������.\n ����� ��� 1200� ���� �� ������ �� ����� ������� ���� ����� �� ��� ������� ������ ��� ��� �� ����.\n ��� ������� ������ ���� ������̡ ����� ��� ������� �� ��� ����� ���� ���� ��� ���� ����� ���� ��� ��� ��� ����� �� ����� ��� ���� ��� ������ ������� ���� �� ���� ��� ������� ��������� ��� ������� ������ ���.");
}
if(x>265&&x<275&&y>124&&y<137){
    jTextArea2.setText("");
    jTextArea2.append(label28.getName()+"\n");
    jTextArea2.append("��� ��� ����� ������� �� ��� �����ɡ �� ��� ������ ������ �� ��� �����ɡ\n ����� ������ ���� ����� ��������");
}
if(x>211&&x<272&&y>207&&y<225){
    jTextArea2.setText("");
    jTextArea2.append(label20.getName()+"\n");
    jTextArea2.append("��� ����� ������� �� ����� ������ ������ ����� ��� �����ɡ\n ����� ����� ������� ��� ����� ������� ��� 1207 ��� �� ������ ���� ����� ��� ��� ����� �� ��� ����� ��� ����� ��� ������� ���� �������\n ����� ����� ������ ������ ������ ������� �� ��� ���� ���� ������ ������ �������, ����� ������ ������ɡ ����� ������� �������");
   
}
if(x>771&&x<818&&y>130&&y<155){
jTextArea2.setText("");
jTextArea2.append(label6.getName()+"\n");
jTextArea2.append("���� ��� ����� ��� ������� ������ <������> ������ ������ ���� ��� ��� 200 � ����� ��� ������� �� ������ ������ ����� ����� ��� ����� ��� ����� ������\n� ��� ��� ����� ����� ����� ����� ��� ���� ������ ����� ����� ��� ����� ����� ��� ����� �������� ���ɡ\n ��� ���� ���������� ��� ����� ���� ����� ��� ��� ����� ����ߡ ����� �� ������� ������� ������� ����� ����� �� ���� ��� ����ȡ ��� �� ���� ����� ������ɡ ����� ������ ��� ���� ������ ������.");

}
if(x>329&&x<351&&y>276&&y<282){
    jTextArea2.setText("");
    jTextArea2.append(label31.getName()+"\n");
    jTextArea2.append("��� ��� ������ ������� ���� ������ ������ � ��� ��� �� ���� ��������� �� �����\n ������ ����� �� ���� �������� �����\n ��� ����� ��� �����ɡ\n ������� ������ ����\n ����� ������ ���� ��� ����֡ ���� �� ����� �����ɡ ���� ����");
    
}
  if(x>797&&x<813&&y<71&&y>40) {
    jTextArea2.setText("");
    jTextArea2.append(label5.getName()+"\n");
    jTextArea2.append(" ��� ������ : ���� ��� ������  ���� 4 ��� ");
      
  }  
  if(x>682&&x<690&&y>13&&y<48){
jTextArea2.setText("");

  jTextArea2.append(label7.getName()+"\n");
  jTextArea2.append("����� ����� ������� ������� ������� ������ ���� ����� ����� ���� ���� �� ��� 1367 \n ��� ���� ���� ���� ������ �������� ������ ����� �� ��� ������� �������� ������� ���� ������ ������ ������ߡ \n ���� ��� ������� �� ����� �������� ����� ������ �����ݡ ��� ��� ��� ���� �������");
  
  
  }
  if(x>426&&x<444&&y>29&&y<51){
jTextArea2.setText("");
jTextArea2.append(label8.getName()+"\n");
jTextArea2.append(" ����� ������ ��� �� ������ �������� ������ ������ ");
  
  }
  if(x>310&&x<343&&y>17&&y<46){
      jTextArea2.setText("");
      jTextArea2.append(label9.getName()+"\n");
      jTextArea2.append("����� �������� ������ ������ �� ����� ������ ������� ������ ������");
  }
  
  if(x>442&&x<456&&y<64&&y>52){
     jTextArea2.setText("");
     jTextArea2.append(label30.getName()+"\n");
     jTextArea2.append("��� �� ������� �������� ������ ������ ������ߡ\n ���� ������� �������� ������ �������� ��� 943�� - 1536� ���� ���� ������.\n ����� ���� ����� ������� ����� �����");
  }
  if(x>168&&x<203&&y>295&&y<310){
   jTextArea2.setText("");
   jTextArea2.append(label16.getName()+"\n");
   
  }
  if(x>177&&x<195&&y>4&&y<25){
      label22.setVisible(true);
  }else
      label22.setVisible(false);
  if(x>155&&x<173&&y>50&&y<64){
      label24.setVisible(true);
  }else
      label24.setVisible(false);
  if(x>149&&x<166&&y>19&&y<33){
      label23.setVisible(true);
  }else
      label23.setVisible(false);
  if(y>150&&y<163&&x>121&&x<135){
      label26.setVisible(true);
  }else
      label26.setVisible(false);
  if(x>148&&x<157&&y>97&&y<122){
      label25.setVisible(true);
  }else
      label25.setVisible(false);
  if(x>113&&x<136&&y>183&&y<209){
      label11.setVisible(true);
  }else
      label11.setVisible(false);
  if(y>158&&y<185&&x>158&&x<170){
      label12.setVisible(true);
  }else
      label12.setVisible(false);
if(x>348&&x<364&&y>46&&y<65){
    label10.setVisible(true);
}else
    label10.setVisible(false);
if(x>154&&x<170&&y>193&&y<206){
    label29.setVisible(true);
}else
    label29.setVisible(false);
if(x>97&&x<104&&y>137&&y<183){
   label19.setVisible(true); 
}else
    label19.setVisible(false);
if(x>78&&x<105&&y>219&&y<233){
    label21.setVisible(true);
}else
    label21.setVisible(false);
if(x>302&&x<318&&y>208&&y<227){
    jTextArea2.setText("");
    jTextArea2.append(label17.getName()+"\n");
    jTextArea2.append("�� ���� ������ ���� ���� ���� ���� �������� ��������ɡ\n ���� ��� ����� ���� ��� 564 �� � 1168�\n ����� ��� ������ ������ ��� ������� �� ���������, ���� ��� ��� �� ���� ���,\n ���� ��� ���� ����� ��� �����ӡ ��� ������� �� ��ȡ\n ���� ��� ���� �� ����� ���� �� ����� ����� ���� ������ ������ ��� ������ ������� �� ������ ������ �������.");
}
    
    }                                    

                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {  
    	jTextArea1.setText(null);
    	Source=null;
    	Source= jComboBox1.getSelectedItem().toString();
    	Distenation=jComboBox2.getSelectedItem().toString();
    	
    	//this for loop to get the city(vertex) name
         for (int i=0 ;i<places.length-3;i++)
    	        {
        	
    	           if( places[i].name.equals((Source)))
    	        		  
    	        	   newSource=places[i];
             
    	          
    	           if(places[i].name.equals((Distenation)))
    	            {
    	             	    
    	        	   newDistenation=places[i];
	             	   
    	           }
    	        }
    	        
    	       if(newSource==null || newDistenation==null)
    	       {
    	
    	    	   JOptionPane.showMessageDialog(null,"Please select a city!!");
    	       }
    	      
    	
               //this method to find paths
    	       Dijkstra.findPaths(newSource);
			// here we find the shortest one
			    List<Vertices> path = v.getShortestPathTo(newDistenation);
			    
			 jTextField1.setText(newDistenation.minDistance + "���");
			 for(int k=0;k<path.size();++k){
				 jTextArea1.append(path.get(k).getName());
				 jTextArea1.append("\n");
			 }
			 newSource=null;
			for (int j=0;j<path.size()-1;j++){
				Graphics  g=jPanel1.getGraphics().create();
		        g.setColor(Color.RED);
				g.drawLine(path.get(j).getX(), path.get(j).getY(), path.get(j+1).getX(), path.get(j+1).getY());
			  
			    
			}
		    	path.clear();
		    	
		
		    	
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        dispose();
    }  
   
    private static void Initial() {
		 
		 for(int i=0;i<places.length;i++)
				places[i]=new Vertices();
		 
		
		 places[0].setName("مسجد قبة الصخرة");
	
		 places[0].setDim(357,151);
		 places[0].placesadj = new Edges[]{ new Edges(places[0], 0),
                
                new Edges(places[18], 60),
                new Edges(places[26], 78),
		         new Edges(places[11], 84),
		         new Edges(places[25], 60)
		 , new Edges(places[9], 218)
		 , new Edges(places[27], 230)
		 , new Edges(places[4], 210),};
		 
		 places[1].setName("المسجد القبلي");
		 places[1].setDim(339,335);
		 places[1].placesadj= new Edges[]{ new Edges(places[1], 0),
                new Edges(places[5], 350),
                new Edges(places[14], 150),
                new Edges(places[13], 50),
                new Edges(places[28], 60),
		 new Edges(places[3], 85)
		 ,new Edges(places[15], 40)
		 
		 };
		 
		 
		 places[2].setName("حائط البراق");
		 places[2].setDim(60,260);
		 places[2].placesadj = new Edges[]{ new Edges(places[2], 0),
                new Edges(places[19], 90),
                new Edges(places[3], 25),
                new Edges(places[15], 60)};
		
		 places[3].setName("باب المغاربة");
		 places[3].setDim(53,306);
		 places[3].placesadj= new Edges[]{new Edges(places[3], 0),
				 new Edges(places[12], 14),
                new Edges(places[15], 45),
                new Edges(places[1], 85)
                ,new Edges(places[2], 25)
               };
		 
		 places[4].setName("باب الأسباط ");
		 places[4].setDim(805,65);
		 places[4].placesadj = new Edges[]{new Edges(places[4], 0), 
				 new Edges(places[5], 120),
                new Edges(places[16], 250),
                new Edges(places[0], 330)
		 ,new Edges(places[6], 80)
		 ,new Edges(places[27], 150)
		 };
		 
		 places[5].setName("باب الرحمة");
		 places[5].setDim(809,144);
		 places[5].placesadj = new Edges[]{ new Edges(places[5], 0),
		            new Edges(places[14], 250),
		            new Edges(places[1], 350),
		            new Edges(places[28], 355),
		            new Edges(places[16], 230)
			                };
		 
		 places[6].setName("مئذنة الأسباط");
		 places[6].setDim(685,34);
		 places[6].placesadj = new Edges[]{ new Edges(places[6], 0),
		            new Edges(places[8], 71),
		            new Edges(places[27], 80),
		            new Edges(places[4], 80)};
		 
		 places[7].setName("باب العتمة");
		 places[7].setDim(324,38);
		 places[7].placesadj = new Edges[]{ new Edges(places[7], 0),
		            new Edges(places[20], 42),
		            new Edges(places[9], 25),
		            new Edges(places[27], 70),
		            new Edges(places[8], 70)
		 };
		 
		 places[8].setName("باب حطة");
		 places[8].setDim(435,43);
		 places[8].placesadj = new Edges[]{ new Edges(places[8], 0),
	              new Edges(places[6], 71),
	              new Edges(places[27], 30),
	              new Edges(places[9], 81),
	              new Edges(places[7], 70)};
		 
		 places[9].setName("قبة سليمان");
		 places[9].setDim(360,52);
		 places[9].placesadj = new Edges[]{ new Edges(places[9], 0),
		            new Edges(places[27], 50),
		            new Edges(places[0], 218),
		            new Edges(places[8], 81),
		            new Edges(places[21], 120)};
		 
		 places[10].setName("باب المطهرة");
		 places[10].setDim(124,200);
		 places[10].placesadj = new Edges[]{ new Edges(places[10], 0),
		            new Edges(places[17], 15),
		            new Edges(places[24], 45),
		            new Edges(places[11], 12),
		            new Edges(places[25], 78),
		           
		            };
		 places[11].setName("سبيل قايتباي");
		 places[11].setDim(165,175);
		 places[11].placesadj = new Edges[]{ new Edges(places[11], 0),
		            new Edges(places[18], 52),
		            new Edges(places[0], 84),
		            new Edges(places[25], 65),
		            new Edges(places[26], 25),
		            new Edges(places[10], 12),
		            new Edges(places[24], 68)};
			

		 places[12].setName("المتحف");
		 places[12].setDim(73,327);
		 places[12].placesadj = new Edges[]{ new Edges(places[12], 0),
		            new Edges(places[13], 20),
		            new Edges(places[3], 14),
		            new Edges(places[15], 33),
		            
		          };
		 
		 places[13].setName("مئذنة باب المغاربة\\ المئذنة الفخارية");
		 places[13].setDim(82,354);
		 places[13].placesadj = new Edges[]{ new Edges(places[13], 0),
		            new Edges(places[12], 20),
		            new Edges(places[15], 50),
		            new Edges(places[1], 50),
		            
		            };
		 
		 places[14].setName("المصلى المرواني ");
		 places[14].setDim(788,314);
		 places[14] .placesadj = new Edges[]{ new Edges(places[14], 0),
		            new Edges(places[5], 250),
		            new Edges(places[1], 150),
		            new Edges(places[16], 230),
		            
		           };
		 
		 places[15].setName("مصطبة الصنوبر");
		 places[15].setDim(187,305);
		 places[15] .placesadj = new Edges[]{ new Edges(places[15], 0),
		            new Edges(places[3], 45),
		            new Edges(places[12], 33),
		            new Edges(places[17], 165),
		            new Edges(places[19], 160)
		           ,new Edges(places[28], 70),
		           new Edges(places[1], 40),
		           new Edges(places[13], 50),
		           new Edges(places[2], 60),
		           
		           };
		 
		 places[16].setName("قبة السلسلة");
		 places[16].setDim(460,172);
		 places[16] .placesadj = new Edges[]{ new Edges(places[16], 0),
		            new Edges(places[5], 230),
		            new Edges(places[0], 38),
		            new Edges(places[27], 210),
		            new Edges(places[4], 250),
		            new Edges(places[18], 90)
		                 };
		
		 places[17].setName("مئذنة باب السلسلة ");
		 places[17].setDim(100,176);
		 places[17] .placesadj = new Edges[]{ new Edges(places[17], 0),
		            new Edges(places[10], 15),
		            new Edges(places[19], 20),
		            new Edges(places[15], 165),
	     new Edges(places[28], 150),
		           };
		
		 places[18].setName("قبة النحوية");
		 places[18].setDim(224,212);
		 places[18] .placesadj = new Edges[]{
		            new Edges(places[18], 0),
		            new Edges(places[28], 70),
		            new Edges(places[26], 32),
		            new Edges(places[16], 90),
		            new Edges(places[25], 60),
		            new Edges(places[0], 60),
		            new Edges(places[11], 52),
		            


		           };
		 
		 places[19].setName("باب السلسلة");
		 places[19].setDim(85,225);
		 places[19] .placesadj = new Edges[]{ new Edges(places[19], 0),
		            new Edges(places[2], 90),
		            new Edges(places[17], 20),
		            new Edges(places[15], 160),
		            new Edges(places[28], 130),
		            new Edges(places[26], 25),
		            new Edges(places[11], 17),
		 
		 
		 };   
		           
		 
		 places[20].setName("مئذنة باب الغوانمة");
		 places[20].setDim(192,8);
		 places[20] .placesadj = new Edges[]{ new Edges(places[20], 0),
		            new Edges(places[21], 50),
		            new Edges(places[7], 42),
		            new Edges(places[9], 78),

		 };
		            
		                   
		 
		 places[21].setName(" باب الغوانمة");
		 places[21].setDim(160,32);
		 places[21] .placesadj = new Edges[]{ new Edges(places[21], 0),
		            new Edges(places[20], 50),
		            new Edges(places[22], 35),
		            new Edges(places[25], 120)};
		            
		                   
		 
		 places[22].setName("باب الناظر");
		 places[22].setDim(158,57);
		 places[22] .placesadj = new Edges[]{ new Edges(places[22], 0),
		            new Edges(places[21], 35),
		            new Edges(places[23], 70),
		            new Edges(places[25], 100),
		            };
		 
		  
		 
		 places[23].setName("باب الحديد");
		 places[23].setDim(150,110);
		 places[23] .placesadj = new Edges[]{ new Edges(places[23], 0),
		            new Edges(places[22], 70),
		            new Edges(places[24], 30),
		            new Edges(places[11], 10),
		            };
		 
		 places[24].setName(" باب القطانين");
		 places[24].setDim(122,158);
		 places[24] .placesadj = new Edges[]{ new Edges(places[24], 0),
		            new Edges(places[23], 30),
		            new Edges(places[10], 45),
		            new Edges(places[11], 15),
		            new Edges(places[26], 140),
		            };
		 
		 
		 places[25].setName("قبة المعراج ");
		 places[25].setDim(282,141);
		 places[25] .placesadj = new Edges[]{ new Edges(places[25], 0),
		            new Edges(places[18], 60),
		            new Edges(places[11], 65),
		            new Edges(places[0], 60),
		            new Edges(places[27], 210),};
		 
		 
		 
		 places[26].setName("قبة النبي موسى ");
		 places[26].setDim(164,200);
		 places[26] .placesadj = new Edges[]{ new Edges(places[26], 0),
		            new Edges(places[28], 105),
		            new Edges(places[18], 32),
		            new Edges(places[11], 25),
		            new Edges(places[19], 25),
		            new Edges(places[0], 78),};
		 
		 
		 
		places[27].setName(" سبيل سليمان");
		 places[27].setDim(449,56);
		 places[27] .placesadj = new Edges[]{ new Edges(places[27], 0),
		            new Edges(places[4], 150),
		            new Edges(places[16], 210),
		            new Edges(places[0], 230),
		            new Edges(places[9], 50),
		            new Edges(places[7], 70),
		            new Edges(places[8], 30),};
		 
		 
		 
		 
		 places[28].setName("سبيل الكأس");
		 places[28].setDim(341,279);
		 places[28] .placesadj = new Edges[]{ new Edges(places[28], 0),
		            new Edges(places[18], 70),
		            new Edges(places[26], 105),
		            new Edges(places[17], 150),
		            new Edges(places[19], 130),
		            new Edges(places[15], 70),
		            new Edges(places[1], 60),
		            new Edges(places[14], 150),
		            new Edges(places[5], 350),};
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
	 }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	Initial();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main1().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label2;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label26;
    private java.awt.Label label27;
    private java.awt.Label label28;
    private java.awt.Label label29;
    private java.awt.Label label3;
    private java.awt.Label label30;
    private java.awt.Label label31;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration                   
}
