/*
 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;

import java.awt.Graphics;
import java.io.File;
import java.util.List;
import java.util.Scanner;

import javax.swing.JOptionPane;

public class NewJFrame extends javax.swing.JFrame {
	String Source;
    String Distenation;
    Vertex newSource;
    Vertex newDistenation;
    static int count=0;
   
    int i=0;

	static Vertex places[]=new Vertex[20];
	static Vertex v;
	

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	 
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        label20 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
     
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jButton4 = new javax.swing.JButton();

        setTitle("جامعة بيرزيت");
        setBackground(java.awt.Color.red);
        setForeground(java.awt.Color.red);

        jPanel1.setLayout(null);
//=------------------------visible/invisible------------------------------
        label1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label1.setName("كلية التكنولوجيا"); // NOI18N
        label1.setText("كلية التكنولوجيا");
        label1.setVisible(true);
        jPanel1.add(label1);
        label1.setBounds(330, 160, 120, 30);

        label2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        label2.setName("مركز نجاد زعني"); // NOI18N
        label2.setText("مركز نجاد زعني");
        label2.setVisible(true);
        jPanel1.add(label2);
        label2.setBounds(300, 300, 110, 30);

        label3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label3.setName("كلية التربية"); // NOI18N
        label3.setText("كلية التربية");
        label3.setVisible(true);
        jPanel1.add(label3);
        label3.setBounds(100, 250, 76, 20);

        label4.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label4.setName("مبنى الرئاسة"); // NOI18N
        label4.setText("مبنى الرئاسة");
        label4.setVisible(true);
        jPanel1.add(label4);
        label4.setBounds(60, 280, 80, 20);

        label5.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label5.setName("كلية الحقوق"); // NOI18N
        label5.setText("كلية الحقوق ");
        label5.setVisible(true);
        jPanel1.add(label5);
        label5.setBounds(768, 40, 80, 20);

        label6.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label6.setName("المكتبة الرئيسية"); // NOI18N
        label6.setText("المكتبة الرئيسية");
        label6.setVisible(true);
        jPanel1.add(label6);
        label6.setBounds(760, 120, 70, 20);

        label7.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label7.setName("كلية الهندسة"); // NOI18N
        label7.setText("كلية الهندسة");
        label7.setVisible(true);
        jPanel1.add(label7);
        label7.setBounds(628, 50, 90, 20);

        label8.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label8.setName("كلية العلوم"); // NOI18N
        label8.setText("كلية العلوم");
        label8.setVisible(true);
        jPanel1.add(label8);
        label8.setBounds(440, 20, 60, 20);

        label9.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label9.setName("كلية التجارة"); // NOI18N
        label9.setText("كلية التجارة");
        label9.setVisible(true);
        jPanel1.add(label9);
        label9.setBounds(280, 10, 100, 20);

        label10.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label10.setName("كلية الرياضة"); // NOI18N
        label10.setText("كلية الرياضة");
        label10.setVisible(true);
        jPanel1.add(label10);
        label10.setBounds(270, 50, 90, 20);

        label11.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label11.setName("كلية التمريض"); // NOI18N
        label11.setText("كلية التمريض");
        label11.setVisible(true);
        jPanel1.add(label11);
        label11.setBounds(130, 130, 90, 20);

        label12.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label12.setName("كلية الآداب"); // NOI18N
        label12.setText("كلية الآداب");
        label12.setVisible(true);
        jPanel1.add(label12);
        label12.setBounds(150, 150, 80, 20);

        label13.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label13.setName("كلية المرأة"); // NOI18N
        label13.setText("كلية المرأة");
        label13.setVisible(true);
        jPanel1.add(label13);
        label13.setBounds(100, 310, 50, 20);

        label14.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label14.setName("كلية الإعلام"); // NOI18N
        label14.setText("كلية الإعلام");
        label14.setVisible(true);
        jPanel1.add(label14);
        label14.setBounds(10, 360, 220, 20);

        label15.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label15.setName("كلية التنمية "); // NOI18N
        label15.setText("كلية التنمية ");
        label15.setVisible(true);
        jPanel1.add(label15);
        label15.setBounds(695, 330, 70, 20);

        label16.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label16.setName("حديقة سمير عويضة"); // NOI18N
        label16.setText("حديقة سمير عويضة");
        label16.setVisible(true);
        jPanel1.add(label16);
        label16.setBounds(190, 280, 100, 20);

        label17.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label17.setName("المدخل الغربي "); // NOI18N
        label17.setText("المدخل الغربي ");
        label17.setVisible(true);
        jPanel1.add(label17);
        label17.setBounds(310, 190, 110, 20);

        label18.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label18.setName("المدخل الشرقي"); // NOI18N
        label18.setText("المدخل الشرقي");
        label18.setVisible(true);
        jPanel1.add(label18);
        label18.setBounds(480, 150, 90, 20);

        label19.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label19.setName("الكافيتيريا الرئيسية "); // NOI18N
        label19.setText("الكافيتيريا الرئيسية ");
        label19.setVisible(true);
        jPanel1.add(label19);
        label19.setBounds(20, 150, 120, 20);

        label20.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label20.setName("قاعة كمال ناصر"); // NOI18N
        label20.setText("قاعة كمال ناصر");
        label20.setVisible(true);
        jPanel1.add(label20);
        label20.setBounds(230, 180, 70, 20);
//--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
       
        jLabel1.setIcon(new javax.swing.ImageIcon("./bzu.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1500, 800);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("المصدر:");

        jComboBox1.setBackground(java.awt.Color.gray);
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setMaximumRowCount(21);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"من",label1.getName(),label2.getName(),label3.getName(),label4.getName(),label5.getName(),label6.getName(),label7.getName(), label8.getName(),label9.getName(),label10.getName(),label11.getName(),label12.getName(),label13.getName(),label14.getName(),label15.getName(),label16.getName(),label17.getName() ,label18.getName(),label19.getName(),label20.getName()}));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("الهدف: ");

        jComboBox2.setBackground(java.awt.Color.gray);
        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setMaximumRowCount(21);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "إلى",label1.getName(),label2.getName(),label3.getName(),label4.getName(),label5.getName(),label6.getName() ,label7.getName(), label8.getName(),label9.getName(),label10.getName(),label11.getName(),label12.getName(),label13.getName(),label14.getName(),label15.getName(),label16.getName(),label17.getName(),label18.getName(),label19.getName(),label20.getName() }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("المسار :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setBackground(java.awt.Color.CYAN);
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("جد الطريق");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("المسافة :");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        

      


        
     
        jButton4.setBackground(java.awt.Color.CYAN);
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("خروج");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(66, 66, 66)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGap(152, 152, 152)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(jTextField3))
                        .addContainerGap())
                    .addComponent(jScrollPane2)))
        );

        pack();
    }// </editor-fold>                        

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {                                   
        int x =evt.getX();
int y=evt.getY();

//==================mouse hovers above labels============================================================
if (x>105&&x<124&&y>890&&y<899){
    
label1.setVisible(true);
}
//else
	//=====================here
  //    label1.setVisible(true);
// =======================to here
if (x>445&&x<475&&y>148&&y<180){
    label18.setVisible(true);
}else
    label18.setVisible(true);

if(x>250&&x<405&&y>295&&y<368){
    label2.setVisible(true);
}
    else
    label2.setVisible(true);
if(x>81&&x<85&&y>317&&y<358){
    label14.setVisible(true);
}
else
    label14.setVisible(true);
if(x>65&&x<95&&y>300&&y<355){
    label13.setVisible(true);
}else
    label13.setVisible(true);
if(y>245&&y<288&&x<86&&x>52){
    label3.setVisible(true);
}
    else
    label3.setVisible(true);

if(x>46&&x<60&&y>298&&y<312){
    label4.setVisible(true);
}else
    label4.setVisible(true);
if(x>539&&x<830&&y>274&&y<407){
    label15.setVisible(true);
}else 
    label15.setVisible(true);
if(x>211&&x<272&&y>207&&y<225){
    label20.setVisible(true);
   
}else
    label20.setVisible(true);
if(x>771&&x<818&&y>130&&y<155){
    label6.setVisible(true);
}else
    label6.setVisible(true);
 if(x>797&&x<813&&y<71&&y>40) {
      label5.setVisible(true);
      
  }   else
      label5.setVisible(true);
  if(x>682&&x<690&&y>13&&y<48){
      label7.setVisible(true);
  }else
      label7.setVisible(true);
  if(x>426&&x<444&&y>29&&y<51){
      label8.setVisible(true);
  }else
      label8.setVisible(true);
  if(x>310&&x<343&&y>17&&y<46){
      label9.setVisible(true);
  }
  else
      label9.setVisible(true);
  if(x>168&&x<203&&y>295&&y<310){
   label16.setVisible(true);
  }else
      label16.setVisible(true);
  if(x>113&&x<136&&y>183&&y<209){
      label11.setVisible(true);
  }else
      label11.setVisible(true);
  if(y>158&&y<185&&x>158&&x<170){
      label12.setVisible(true);
  }else
      label12.setVisible(true);
if(x>348&&x<364&&y>46&&y<65){
    label10.setVisible(true);
}else
    label10.setVisible(true);
if(x>97&&x<104&&y>137&&y<183){
   label19.setVisible(true); 
}else
    label19.setVisible(true);
if(x>302&&x<318&&y>208&&y<227){
    label17.setVisible(true);
}else
    label17.setVisible(true);
    }                                  
//==========================================ending mouse hovers above labels
    
    //===========================visible/invisible ends here---------------------------------------------------------
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {                                     
int x =evt.getX();
int y=evt.getY();

if (x>305&&x<424&&y>90&&y<190){

}

if (x>445&&x<475&&y>148&&y<180){
//jTextArea2.append(label18.getName()+"\n");

}
if(x>250&&x<405&&y>295&&y<368){
//    jTextArea2.append(label2.getName()+"\n");

}
   
if(x>81&&x<85&&y>317&&y<358){
//	jTextArea2.append(label14.getName()+"\n");


}

if(x>65&&x<95&&y>300&&y<355){
//	jTextArea2.append(label13.getName()+"\n");

}
if(y>245&&y<288&&x<86&&x>52){
//	jTextArea2.append(label3.getName()+"\n");

}
   
if(x>46&&x<60&&y>298&&y<312){
  // jTextArea2.append(label4.getName()+"\n");


}
if(x>539&&x<830&&y>274&&y<407){
//    jTextArea2.append(label15.getName()+"\n");


}
if(x>278&&x<289&&y>128&&y<151){
//   jTextArea2.append(label27.getName()+"\n");


}
if(x>265&&x<275&&y>124&&y<137){
//    jTextArea2.append(label28.getName()+"\n");

	
}
if(x>211&&x<272&&y>207&&y<225){
    //jTextArea2.append(label20.getName()+"\n");
   
}
if(x>771&&x<818&&y>130&&y<155){
//jTextArea2.append(label6.getName()+"\n");


}
if(x>329&&x<351&&y>276&&y<282){
//    jTextArea2.append(label31.getName()+"\n");
    
}
  if(x>797&&x<813&&y<71&&y>40) {
 //   jTextArea2.append(label5.getName()+"\n");
      
  }  
  if(x>682&&x<690&&y>13&&y<48){

//  jTextArea2.append(label7.getName()+"\n");
  
  
  }
  if(x>426&&x<444&&y>29&&y<51){
//jTextArea2.append(label8.getName()+"\n");
  
  }
  if(x>310&&x<343&&y>17&&y<46){
  //    jTextArea2.append(label9.getName()+"\n");
  
  }
  
  if(x>442&&x<456&&y<64&&y>52){
  //   jTextArea2.append(label30.getName()+"\n");


  }
  if(x>168&&x<203&&y>295&&y<310){
//   jTextArea2.append(label16.getName()+"\n");
   
  }
  if(x>113&&x<136&&y>183&&y<209){
      label11.setVisible(true);
  }else
      label11.setVisible(false);
  if(y>158&&y<185&&x>158&&x<170){
      label12.setVisible(true);
  }else
      label12.setVisible(false);
if(x>348&&x<364&&y>46&&y<65){
    label10.setVisible(true);
}else
    label10.setVisible(false);
if(x>97&&x<104&&y>137&&y<183){
   label19.setVisible(true); 
}else
    label19.setVisible(false);
if(x>302&&x<318&&y>208&&y<227){

	//    jTextArea2.append(label17.getName()+"\n");



}
    
    }                                    

                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {  
    	jTextArea1.setText(null);
    	
    	
    	Source=null;
    	Source= jComboBox1.getSelectedItem().toString();
    	Distenation=jComboBox2.getSelectedItem().toString();
    	
    	//this for loop to get the city(vertex) name
         for (int i=0 ;i<places.length-3;i++)
    	        {
        	
    	           if( places[i].name.equals((Source)))
    	        		  
    	        	   newSource=places[i];
             
    	          
    	           if(places[i].name.equals((Distenation)))
    	            {
    	             	    
    	        	   newDistenation=places[i];
	             	   
    	           }
    	        }
    	        
    	       if(newSource==null || newDistenation==null)
    	       {
    	
    	    	   JOptionPane.showMessageDialog(null,"الرجاء اختيار المكان");
    	       }
    	      
    	
               //this method to find paths
    	       Dijiksrah.findPaths(newSource);
			// here we find the shortest one
			    List<Vertex> path = v.getShortestPathTo(newDistenation);
			    
			 jTextField1.setText(newDistenation.minDistance + "  "+"متر");
			 for(int k=0;k<path.size();++k){
				 jTextArea1.append(path.get(k).getName());
				 jTextArea1.append("\n");
			 }
			 newSource=null;
			for (int j=0;j<path.size()-1;j++){
				Graphics  g=jPanel1.getGraphics().create();
		        g.setColor(Color.RED);
				g.drawLine(path.get(j).getX(), path.get(j).getY(), path.get(j+1).getX(), path.get(j+1).getY());
			  
			    
			}
		    	path.clear();
		    	
		
		    	
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        dispose();
    }  
   
    private static void Initial() {
		 
		 for(int i=0;i<places.length;i++)
				places[i]=new Vertex();
		 
		
		 places[0].setName("كلية التكنولوجيا");
	
		 places[0].setDim(357,151);
		 places[0].placesadj = new Edge[]{ new Edge(places[0], 0),
                new Edge(places[10], 230),
                 new Edge(places[1], 40)
		        , new Edge(places[13], 136)
		 
		 };
		 
		 places[1].setName("مركز نجاد زعني");
		 places[1].setDim(339,335);
		 places[1].placesadj= new Edge[]{ new Edge(places[1], 0),
                new Edge(places[0], 40),
                new Edge(places[2], 55),
                new Edge(places[13], 100),
    	 
		 };
		 
		 
		 places[2].setName("كلية التربية");
		 places[2].setDim(60,260);
		 places[2].placesadj = new Edge[]{ new Edge(places[2], 0),
                new Edge(places[1], 55),
                new Edge(places[3], 291),
                new Edge(places[4], 280),
                new Edge(places[11], 100),
                new Edge(places[12], 110),
                  
		 };
		
		 places[3].setName("مبني الرئاسة");
		 places[3].setDim(53,306);
		 places[3].placesadj= new Edge[]{new Edge(places[3], 0),
				 new Edge(places[2], 291),
                new Edge(places[4], 90),
             
		 };
		 
		 places[4].setName("كلية الحقوق ");
		 places[4].setDim(805,65);
		 places[4].placesadj = new Edge[]{new Edge(places[4], 0), 
		
			    new Edge(places[2], 280),
                new Edge(places[3], 90),
                new Edge(places[18], 60)
		       ,new Edge(places[5], 180)
	           ,new Edge(places[6], 222)
               ,new Edge(places[8], 295)
               ,new Edge(places[19], 91)
		       ,new Edge(places[15], 133)
	           ,new Edge(places[17], 290)
	          
		 };
		 
		 places[5].setName("المكتبة الرئيسية");
		 places[5].setDim(809,144);
		 places[5].placesadj = new Edge[]{ new Edge(places[5], 0),
		            new Edge(places[4], 180),
		            new Edge(places[7], 201),
		            new Edge(places[8], 100),
			           
		 };
		 
		 places[6].setName("كلية الهندسة");
		 places[6].setDim(685,34);
		 places[6].placesadj = new Edge[]{ new Edge(places[6], 0),
		 
			      new Edge(places[4], 222),
		          new Edge(places[7], 150)
                 ,new Edge(places[16], 82)
                 ,new Edge(places[9], 330)
		          ,new Edge(places[18], 153)
                   ,new Edge(places[19], 120)
				 
		 
		 };
		 
		 
		 places[7].setName("كلية العلوم");
		 places[7].setDim(324,38);
		 places[7].placesadj = new Edge[]{ new Edge(places[7], 0),
		            new Edge(places[6], 150),
		            new Edge(places[16], 115)
                    ,new Edge(places[8], 240)
                      ,new Edge(places[5], 201)
		 
		 
		 };
		 
		 places[8].setName("كلية التجارة");
		 places[8].setDim(435,43);
		 places[8].placesadj = new Edge[]{ new Edge(places[8], 0),
	              new Edge(places[7], 240),
	              new Edge(places[4], 295),
	              new Edge(places[5], 100)
                  ,new Edge(places[17], 223)
			
		 
		 };
		 
		 places[9].setName("كلية الرياضة");
		 places[9].setDim(360,52);
		 places[9].placesadj = new Edge[]{ new Edge(places[9], 0),
		            new Edge(places[6], 330),
		            new Edge(places[10], 270),
		            new Edge(places[11], 90),
		            new Edge(places[15], 120),
		            		            
		         };
		 
		 places[10].setName("كلية التمريض");
		 places[10].setDim(124,200);
		 places[10].placesadj = new Edge[]{ new Edge(places[10], 0),
		            new Edge(places[9], 270),
		            new Edge(places[0], 230),
		            new Edge(places[11], 208),
		            new Edge(places[13], 110),
		            new Edge(places[12], 160),
				            
			              
		            };
		 places[11].setName("كلية الآداب");
		 places[11].setDim(165,175);
		 places[11].placesadj = new Edge[]{ new Edge(places[11], 0),
		            new Edge(places[10], 208),
		            new Edge(places[12], 35),
		            new Edge(places[15], 77),
		            new Edge(places[2], 100),
		            
		         };
			

		 places[12].setName("كلية المرأة");
		 places[12].setDim(73,327);
		 places[12].placesadj = new Edge[]{ new Edge(places[12], 0),
		            new Edge(places[11], 35),
		            new Edge(places[10], 160),
		            new Edge(places[13], 60),
		            new Edge(places[14], 29),
		            
		          };
		 
		 places[13].setName("كلية الإعلام");
		 places[13].setDim(82,354);
		 places[13].placesadj = new Edge[]{ new Edge(places[13], 0),
		            new Edge(places[12], 60),
		            new Edge(places[14], 33),
		            new Edge(places[10], 110),
		            new Edge(places[0], 136),
		            new Edge(places[1], 100),
		            
		            };
		 
		 places[14].setName("كلية التنمية ");
		 places[14].setDim(788,314);
		 places[14] .placesadj = new Edge[]{ new Edge(places[14], 0),
		            new Edge(places[13], 33),
		            new Edge(places[12], 29),
		            
		           };
		 
		 places[15].setName("حديقة سمير عويضة");
		 places[15].setDim(187,305);
		 places[15] .placesadj = new Edge[]{ new Edge(places[15], 0),
		            new Edge(places[11], 77),
		            new Edge(places[9], 120),
		            new Edge(places[18], 113),
		            new Edge(places[4], 133),
			           
		           };
		 
		 places[16].setName("المدخل الغربي");
		 places[16].setDim(460,172);
		 places[16] .placesadj = new Edge[]{ new Edge(places[16], 0),
		            new Edge(places[6], 82),
		            new Edge(places[7],115),
		                 };
		
		 places[17].setName("المدخل الشرقي ");
		 places[17].setDim(100,176);
		 places[17] .placesadj = new Edge[]{ new Edge(places[17], 0),
		            new Edge(places[8], 223),
		            new Edge(places[19], 20),
		            new Edge(places[4], 290),
		            
		        
		 };
		
		 places[18].setName("الكافتيريا الرئيسية");
		 places[18].setDim(224,212);
		 places[18] .placesadj = new Edge[]{
		            new Edge(places[4], 60),
		            new Edge(places[15], 113),
		            new Edge(places[6], 153),
				    
		           };
		 
		 places[19].setName("قاعة كمال ناصر");
		 places[19].setDim(85,225);
		 places[19] .placesadj = new Edge[]{ new Edge(places[19], 0),
		            new Edge(places[4], 91),
		            new Edge(places[6], 120),
		 
		 };   
		 
	 }
  //--------------------------------Variable declaration + look and feel info------------------------------------------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	Initial();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label2;
    private java.awt.Label label20;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration                   
}
